//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.11 at 02:01:32 PM EEST 
//


package org.dmg.pmml_3_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.dmg.org/PMML-3_1}euclidean"/>
 *           &lt;element ref="{http://www.dmg.org/PMML-3_1}squaredEuclidean"/>
 *           &lt;element ref="{http://www.dmg.org/PMML-3_1}chebychev"/>
 *           &lt;element ref="{http://www.dmg.org/PMML-3_1}cityBlock"/>
 *           &lt;element ref="{http://www.dmg.org/PMML-3_1}minkowski"/>
 *           &lt;element ref="{http://www.dmg.org/PMML-3_1}simpleMatching"/>
 *           &lt;element ref="{http://www.dmg.org/PMML-3_1}jaccard"/>
 *           &lt;element ref="{http://www.dmg.org/PMML-3_1}tanimoto"/>
 *           &lt;element ref="{http://www.dmg.org/PMML-3_1}binarySimilarity"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="kind" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="distance"/>
 *             &lt;enumeration value="similarity"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="compareFunction" type="{http://www.dmg.org/PMML-3_1}COMPARE-FUNCTION" default="absDiff" />
 *       &lt;attribute name="minimum" type="{http://www.dmg.org/PMML-3_1}NUMBER" />
 *       &lt;attribute name="maximum" type="{http://www.dmg.org/PMML-3_1}NUMBER" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extension",
    "euclidean",
    "squaredEuclidean",
    "chebychev",
    "cityBlock",
    "minkowski",
    "simpleMatching",
    "jaccard",
    "tanimoto",
    "binarySimilarity"
})
@XmlRootElement(name = "ComparisonMeasure")
public class ComparisonMeasure {

    @XmlElement(name = "Extension")
    protected List<Extension> extension;
    protected Euclidean euclidean;
    protected SquaredEuclidean squaredEuclidean;
    protected Chebychev chebychev;
    protected CityBlock cityBlock;
    protected Minkowski minkowski;
    protected SimpleMatching simpleMatching;
    protected Jaccard jaccard;
    protected Tanimoto tanimoto;
    protected BinarySimilarity binarySimilarity;
    @XmlAttribute(name = "kind", required = true)
    protected ComparisonMeasure.Kind kind;
    @XmlAttribute(name = "compareFunction")
    protected CompareFunction compareFunction;
    @XmlAttribute(name = "minimum")
    protected Double minimum;
    @XmlAttribute(name = "maximum")
    protected Double maximum;

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * 
     * 
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Extension>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the euclidean property.
     * 
     * @return
     *     possible object is
     *     {@link Euclidean }
     *     
     */
    public Euclidean getEuclidean() {
        return euclidean;
    }

    /**
     * Sets the value of the euclidean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Euclidean }
     *     
     */
    public void setEuclidean(Euclidean value) {
        this.euclidean = value;
    }

    /**
     * Gets the value of the squaredEuclidean property.
     * 
     * @return
     *     possible object is
     *     {@link SquaredEuclidean }
     *     
     */
    public SquaredEuclidean getSquaredEuclidean() {
        return squaredEuclidean;
    }

    /**
     * Sets the value of the squaredEuclidean property.
     * 
     * @param value
     *     allowed object is
     *     {@link SquaredEuclidean }
     *     
     */
    public void setSquaredEuclidean(SquaredEuclidean value) {
        this.squaredEuclidean = value;
    }

    /**
     * Gets the value of the chebychev property.
     * 
     * @return
     *     possible object is
     *     {@link Chebychev }
     *     
     */
    public Chebychev getChebychev() {
        return chebychev;
    }

    /**
     * Sets the value of the chebychev property.
     * 
     * @param value
     *     allowed object is
     *     {@link Chebychev }
     *     
     */
    public void setChebychev(Chebychev value) {
        this.chebychev = value;
    }

    /**
     * Gets the value of the cityBlock property.
     * 
     * @return
     *     possible object is
     *     {@link CityBlock }
     *     
     */
    public CityBlock getCityBlock() {
        return cityBlock;
    }

    /**
     * Sets the value of the cityBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link CityBlock }
     *     
     */
    public void setCityBlock(CityBlock value) {
        this.cityBlock = value;
    }

    /**
     * Gets the value of the minkowski property.
     * 
     * @return
     *     possible object is
     *     {@link Minkowski }
     *     
     */
    public Minkowski getMinkowski() {
        return minkowski;
    }

    /**
     * Sets the value of the minkowski property.
     * 
     * @param value
     *     allowed object is
     *     {@link Minkowski }
     *     
     */
    public void setMinkowski(Minkowski value) {
        this.minkowski = value;
    }

    /**
     * Gets the value of the simpleMatching property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleMatching }
     *     
     */
    public SimpleMatching getSimpleMatching() {
        return simpleMatching;
    }

    /**
     * Sets the value of the simpleMatching property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleMatching }
     *     
     */
    public void setSimpleMatching(SimpleMatching value) {
        this.simpleMatching = value;
    }

    /**
     * Gets the value of the jaccard property.
     * 
     * @return
     *     possible object is
     *     {@link Jaccard }
     *     
     */
    public Jaccard getJaccard() {
        return jaccard;
    }

    /**
     * Sets the value of the jaccard property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jaccard }
     *     
     */
    public void setJaccard(Jaccard value) {
        this.jaccard = value;
    }

    /**
     * Gets the value of the tanimoto property.
     * 
     * @return
     *     possible object is
     *     {@link Tanimoto }
     *     
     */
    public Tanimoto getTanimoto() {
        return tanimoto;
    }

    /**
     * Sets the value of the tanimoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tanimoto }
     *     
     */
    public void setTanimoto(Tanimoto value) {
        this.tanimoto = value;
    }

    /**
     * Gets the value of the binarySimilarity property.
     * 
     * @return
     *     possible object is
     *     {@link BinarySimilarity }
     *     
     */
    public BinarySimilarity getBinarySimilarity() {
        return binarySimilarity;
    }

    /**
     * Sets the value of the binarySimilarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinarySimilarity }
     *     
     */
    public void setBinarySimilarity(BinarySimilarity value) {
        this.binarySimilarity = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link ComparisonMeasure.Kind }
     *     
     */
    public ComparisonMeasure.Kind getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComparisonMeasure.Kind }
     *     
     */
    public void setKind(ComparisonMeasure.Kind value) {
        this.kind = value;
    }

    /**
     * Gets the value of the compareFunction property.
     * 
     * @return
     *     possible object is
     *     {@link CompareFunction }
     *     
     */
    public CompareFunction getCompareFunction() {
        if (compareFunction == null) {
            return CompareFunction.ABS_DIFF;
        } else {
            return compareFunction;
        }
    }

    /**
     * Sets the value of the compareFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompareFunction }
     *     
     */
    public void setCompareFunction(CompareFunction value) {
        this.compareFunction = value;
    }

    /**
     * Gets the value of the minimum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinimum() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinimum(Double value) {
        this.minimum = value;
    }

    /**
     * Gets the value of the maximum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaximum() {
        return maximum;
    }

    /**
     * Sets the value of the maximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaximum(Double value) {
        this.maximum = value;
    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="distance"/>
     *     &lt;enumeration value="similarity"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum Kind {

        @XmlEnumValue("distance")
        DISTANCE("distance"),
        @XmlEnumValue("similarity")
        SIMILARITY("similarity");
        private final String value;

        Kind(String v) {
            value = v;
        }

        public String value() {
            return value;
        }

        public static ComparisonMeasure.Kind fromValue(String v) {
            for (ComparisonMeasure.Kind c: ComparisonMeasure.Kind.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
            throw new IllegalArgumentException(v);
        }

    }

}
