//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.11 at 02:01:32 PM EEST 
//


package org.dmg.pmml_3_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DELIMITER.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DELIMITER">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="sameTimeWindow"/>
 *     &lt;enumeration value="acrossTimeWindows"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DELIMITER")
@XmlEnum
public enum DelimiterType {

    @XmlEnumValue("sameTimeWindow")
    SAME_TIME_WINDOW("sameTimeWindow"),
    @XmlEnumValue("acrossTimeWindows")
    ACROSS_TIME_WINDOWS("acrossTimeWindows");
    private final String value;

    DelimiterType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DelimiterType fromValue(String v) {
        for (DelimiterType c: DelimiterType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
