//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.11 at 02:01:32 PM EEST 
//


package org.dmg.pmml_3_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}MiningSchema"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}Output" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}ModelStats" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}Targets" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}LocalTransformations" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}ParameterList"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}FactorList" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}CovariateList" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}PPMatrix"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}PCovMatrix" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}ParamMatrix"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}ModelVerification" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="targetVariableName" type="{http://www.dmg.org/PMML-3_1}FIELD-NAME" />
 *       &lt;attribute name="modelType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="regression"/>
 *             &lt;enumeration value="generalLinear"/>
 *             &lt;enumeration value="multinomialLogistic"/>
 *             &lt;enumeration value="ordinalMultinomial"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="modelName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="functionName" use="required" type="{http://www.dmg.org/PMML-3_1}MINING-FUNCTION" />
 *       &lt;attribute name="algorithmName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cumulativeLink" type="{http://www.dmg.org/PMML-3_1}LINK-FUNCTION" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "GeneralRegressionModel")
public class GeneralRegressionModel {

    @XmlElementRefs({
        @XmlElementRef(name = "CovariateList", namespace = "http://www.dmg.org/PMML-3_1", type = CovariateList.class, required = false),
        @XmlElementRef(name = "ModelVerification", namespace = "http://www.dmg.org/PMML-3_1", type = ModelVerification.class, required = false),
        @XmlElementRef(name = "Targets", namespace = "http://www.dmg.org/PMML-3_1", type = Targets.class, required = false),
        @XmlElementRef(name = "LocalTransformations", namespace = "http://www.dmg.org/PMML-3_1", type = LocalTransformations.class, required = false),
        @XmlElementRef(name = "PCovMatrix", namespace = "http://www.dmg.org/PMML-3_1", type = PCovMatrix.class, required = false),
        @XmlElementRef(name = "PPMatrix", namespace = "http://www.dmg.org/PMML-3_1", type = PPMatrix.class, required = false),
        @XmlElementRef(name = "Extension", namespace = "http://www.dmg.org/PMML-3_1", type = Extension.class, required = false),
        @XmlElementRef(name = "MiningSchema", namespace = "http://www.dmg.org/PMML-3_1", type = MiningSchema.class, required = false),
        @XmlElementRef(name = "ModelStats", namespace = "http://www.dmg.org/PMML-3_1", type = ModelStats.class, required = false),
        @XmlElementRef(name = "ParameterList", namespace = "http://www.dmg.org/PMML-3_1", type = ParameterList.class, required = false),
        @XmlElementRef(name = "FactorList", namespace = "http://www.dmg.org/PMML-3_1", type = FactorList.class, required = false),
        @XmlElementRef(name = "ParamMatrix", namespace = "http://www.dmg.org/PMML-3_1", type = ParamMatrix.class, required = false),
        @XmlElementRef(name = "Output", namespace = "http://www.dmg.org/PMML-3_1", type = Output.class, required = false)
    })
    protected List<Object> content;
    @XmlAttribute(name = "targetVariableName")
    protected String targetVariableName;
    @XmlAttribute(name = "modelType", required = true)
    protected GeneralRegressionModel.ModelType modelType;
    @XmlAttribute(name = "modelName")
    protected String modelName;
    @XmlAttribute(name = "functionName", required = true)
    protected MiningFunction functionName;
    @XmlAttribute(name = "algorithmName")
    protected String algorithmName;
    @XmlAttribute(name = "cumulativeLink")
    protected LinkFunction cumulativeLink;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Extension" is used by two different parts of a schema. See: 
     * line 1808 of file:/D:/Work/workspace/PMMLAnalizer/xml-resources/jaxb/PMML_3_1/pmml-3-1.xsd
     * line 1794 of file:/D:/Work/workspace/PMMLAnalizer/xml-resources/jaxb/PMML_3_1/pmml-3-1.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CovariateList }
     * {@link ModelVerification }
     * {@link Targets }
     * {@link LocalTransformations }
     * {@link PCovMatrix }
     * {@link PPMatrix }
     * {@link Extension }
     * {@link MiningSchema }
     * {@link ModelStats }
     * {@link ParameterList }
     * {@link FactorList }
     * {@link ParamMatrix }
     * {@link Output }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the targetVariableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetVariableName() {
        return targetVariableName;
    }

    /**
     * Sets the value of the targetVariableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetVariableName(String value) {
        this.targetVariableName = value;
    }

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralRegressionModel.ModelType }
     *     
     */
    public GeneralRegressionModel.ModelType getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralRegressionModel.ModelType }
     *     
     */
    public void setModelType(GeneralRegressionModel.ModelType value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the functionName property.
     * 
     * @return
     *     possible object is
     *     {@link MiningFunction }
     *     
     */
    public MiningFunction getFunctionName() {
        return functionName;
    }

    /**
     * Sets the value of the functionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiningFunction }
     *     
     */
    public void setFunctionName(MiningFunction value) {
        this.functionName = value;
    }

    /**
     * Gets the value of the algorithmName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlgorithmName() {
        return algorithmName;
    }

    /**
     * Sets the value of the algorithmName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlgorithmName(String value) {
        this.algorithmName = value;
    }

    /**
     * Gets the value of the cumulativeLink property.
     * 
     * @return
     *     possible object is
     *     {@link LinkFunction }
     *     
     */
    public LinkFunction getCumulativeLink() {
        return cumulativeLink;
    }

    /**
     * Sets the value of the cumulativeLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkFunction }
     *     
     */
    public void setCumulativeLink(LinkFunction value) {
        this.cumulativeLink = value;
    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="regression"/>
     *     &lt;enumeration value="generalLinear"/>
     *     &lt;enumeration value="multinomialLogistic"/>
     *     &lt;enumeration value="ordinalMultinomial"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum ModelType {

        @XmlEnumValue("regression")
        REGRESSION("regression"),
        @XmlEnumValue("generalLinear")
        GENERAL_LINEAR("generalLinear"),
        @XmlEnumValue("multinomialLogistic")
        MULTINOMIAL_LOGISTIC("multinomialLogistic"),
        @XmlEnumValue("ordinalMultinomial")
        ORDINAL_MULTINOMIAL("ordinalMultinomial");
        private final String value;

        ModelType(String v) {
            value = v;
        }

        public String value() {
            return value;
        }

        public static GeneralRegressionModel.ModelType fromValue(String v) {
            for (GeneralRegressionModel.ModelType c: GeneralRegressionModel.ModelType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
            throw new IllegalArgumentException(v);
        }

    }

}
