//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.11 at 02:01:32 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dmg.org/PMML-3_1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.dmg.pmml_3_1;
