//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.10.11 at 02:01:32 PM EEST
//


package org.dmg.pmml_3_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}Header"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}MiningBuildTask" minOccurs="0"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}DataDictionary"/>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}TransformationDictionary" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;choice>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}AssociationModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}ClusteringModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}GeneralRegressionModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}MiningModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}NaiveBayesModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}NeuralNetwork"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}RegressionModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}RuleSetModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}SequenceModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}SupportVectorMachineModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}TextModel"/>
 *             &lt;element ref="{http://www.dmg.org/PMML-3_1}TreeModel"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.dmg.org/PMML-3_1}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "miningBuildTask",
    "dataDictionary",
    "transformationDictionary",
    "model",
    "extension"
})
@XmlRootElement(name = "PMML")
public class PMML {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "MiningBuildTask")
    protected MiningBuildTask miningBuildTask;
    @XmlElement(name = "DataDictionary", required = true)
    protected DataDictionary dataDictionary;
    @XmlElement(name = "TransformationDictionary")
    protected TransformationDictionary transformationDictionary;
    @XmlElements({
        @XmlElement(name = "NeuralNetwork", type = NeuralNetwork.class),
        @XmlElement(name = "AssociationModel", type = AssociationModel.class),
        @XmlElement(name = "ClusteringModel", type = ClusteringModel.class),
        @XmlElement(name = "RuleSetModel", type = RuleSetModel.class),
        @XmlElement(name = "NaiveBayesModel", type = NaiveBayesModel.class),
        @XmlElement(name = "SupportVectorMachineModel", type = SupportVectorMachineModel.class),
        @XmlElement(name = "SequenceModel", type = SequenceModel.class),
        @XmlElement(name = "TextModel", type = TextModel.class),
        @XmlElement(name = "TreeModel", type = TreeModel.class),
        @XmlElement(name = "GeneralRegressionModel", type = GeneralRegressionModel.class),
        @XmlElement(name = "MiningModel", type = MiningModel.class),
        @XmlElement(name = "RegressionModel", type = RegressionModel.class)
    })
    protected List<Object> model;
    @XmlElement(name = "Extension")
    protected List<Extension> extension;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    public static <T> T safeCast(Object rawObject, Class<T> targetType) {
        if ( targetType.isInstance(rawObject) ) {
            return targetType.cast(rawObject);
        }
        return null;
    }

    public static <T> T findTargetTypeObject(List<Object> rawContent, Class<T> targetType) {
        for ( Object rawObject : rawContent ) {
            if ( targetType.isInstance(rawObject) ) {
                return targetType.cast(rawObject);
            }
        }
        return null;
    }

    public static <T> List<T> findTargetTypeObjects(List<Object> rawContent, Class<T> targetType) {
        List<T> result = new ArrayList<T>();
        for ( Object rawObject : rawContent ) {
            if ( targetType.isInstance(rawObject) ) {
                result.add(targetType.cast(rawObject));
            }
        }
        return result;
    }

    /**
     * Gets the value of the header property.
     *
     * @return
     *     possible object is
     *     {@link Header }
     *
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value
     *     allowed object is
     *     {@link Header }
     *
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the miningBuildTask property.
     *
     * @return
     *     possible object is
     *     {@link MiningBuildTask }
     *
     */
    public MiningBuildTask getMiningBuildTask() {
        return miningBuildTask;
    }

    /**
     * Sets the value of the miningBuildTask property.
     *
     * @param value
     *     allowed object is
     *     {@link MiningBuildTask }
     *
     */
    public void setMiningBuildTask(MiningBuildTask value) {
        this.miningBuildTask = value;
    }

    /**
     * Gets the value of the dataDictionary property.
     *
     * @return
     *     possible object is
     *     {@link DataDictionary }
     *
     */
    public DataDictionary getDataDictionary() {
        return dataDictionary;
    }

    /**
     * Sets the value of the dataDictionary property.
     *
     * @param value
     *     allowed object is
     *     {@link DataDictionary }
     *
     */
    public void setDataDictionary(DataDictionary value) {
        this.dataDictionary = value;
    }

    /**
     * Gets the value of the transformationDictionary property.
     *
     * @return
     *     possible object is
     *     {@link TransformationDictionary }
     *
     */
    public TransformationDictionary getTransformationDictionary() {
        return transformationDictionary;
    }

    /**
     * Sets the value of the transformationDictionary property.
     *
     * @param value
     *     allowed object is
     *     {@link TransformationDictionary }
     *
     */
    public void setTransformationDictionary(TransformationDictionary value) {
        this.transformationDictionary = value;
    }

    /**
     * Gets the value of the model property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the model property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModel().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NeuralNetwork }
     * {@link AssociationModel }
     * {@link ClusteringModel }
     * {@link RuleSetModel }
     * {@link NaiveBayesModel }
     * {@link SupportVectorMachineModel }
     * {@link SequenceModel }
     * {@link TextModel }
     * {@link TreeModel }
     * {@link GeneralRegressionModel }
     * {@link MiningModel }
     * {@link RegressionModel }
     *
     *
     */
    public List<Object> getModel() {
        if (model == null) {
            model = new ArrayList<Object>();
        }
        return this.model;
    }

    public TreeModel getTreeModel() {
        return findTargetTypeObject(model, TreeModel.class);
    }

    /**
     * Gets the value of the extension property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     *
     *
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Extension>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
