//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.11 at 02:01:32 PM EEST 
//


package org.dmg.pmml_3_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SVM-REPRESENTATION.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SVM-REPRESENTATION">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SupportVectors"/>
 *     &lt;enumeration value="Coefficients"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SVM-REPRESENTATION")
@XmlEnum
public enum SvmRepresentation {

    @XmlEnumValue("SupportVectors")
    SUPPORT_VECTORS("SupportVectors"),
    @XmlEnumValue("Coefficients")
    COEFFICIENTS("Coefficients");
    private final String value;

    SvmRepresentation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SvmRepresentation fromValue(String v) {
        for (SvmRepresentation c: SvmRepresentation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
